name: CI

on: push

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: yarn

    - name: Install packages
      run: yarn install --pure-lockfile --prefer-offline

    - name: Setup test database
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      run: bundle exec rails db:setup

    - name: Run tests
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      run: |
        bundle exec rake
        TEST_BROWSER=headless_chrome bundle exec rake test:system
